[workspace]
members = [
    "crates/vk-video-core",
    "crates/vk-video-parser",
    "crates/vk-video-vulkan",
    "crates/examples",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Vulkan Video Decoder library in Rust"
repository = "https://github.com/andreytkachenko/vk-video"

[workspace.dependencies]
vk-video-core = { path = "crates/vk-video-core", version = "0.1.0" }
vk-video-vulkan = { path = "crates/vk-video-vulkan", version = "0.1.0" }
vk-video-parser = { path = "crates/vk-video-parser", version = "0.1.0" }
ash = "0.38"
bytemuck = { version = "1", features = ["derive"] }
bitflags = "2"
thiserror = "2"
log = "0.4"
tracing = "0.1"
