#!/usr/bin/env python3
"""
Pixel-verification script for Vulkan video decoder.

Compares Vulkan hardware-decoded frames against ffmpeg software-decoded frames
using PSNR metrics per frame.

Usage:
    python pixel-verify.py <bitstream> [max_frames]
    python pixel-verify.py born_trailer.h264 20
"""

import argparse
import glob
import math
import os
import shutil
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent
EXAMPLE_BIN = PROJECT_ROOT / "target/release/examples/vulkan_decode"
YUV_STEPS = [0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0, 5.0, 10.0, 50.0, 100.0, 500.0, 1000.0]
TMP_DIR = Path("/tmp/pixel_verify")


def numeric_sort_key(path):
    """Extract numeric frame index from path for proper sorting."""
    stem = Path(path).stem
    # Handle patterns like "stem_frame_N" or "stem_ffmpeg_frame_N"
    parts = stem.rsplit("_", 1)
    if len(parts) == 2:
        try:
            return int(parts[1])
        except ValueError:
            pass
    return 0


def ensure_tmp_dir():
    """Create temp directory for YUV files."""
    TMP_DIR.mkdir(parents=True, exist_ok=True)


def clean_yuv_files(stem: str):
    """Remove all previously generated YUV files for the given stem."""
    patterns = [
        f"{stem}_frame_*.yuv",
        f"{stem}_ffmpeg_frame_*.yuv",
    ]
    for pattern in patterns:
        for path in glob.glob(str(TMP_DIR / pattern)):
            os.remove(path)


def build_example():
    """Fresh cargo build --release of vulkan_decode example."""
    print("Building vulkan_decode example (--release)...")
    result = subprocess.run(
        ["cargo", "build", "--release", "--example", "vulkan_decode"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("Build failed!")
        print(result.stderr)
        sys.exit(1)
    print("Build succeeded.")


def run_vulkan_decode(bitstream: str, max_frames: int):
    """Run the Vulkan decoder to generate YUV frames."""
    stem = Path(bitstream).stem
    abs_bitstream = os.path.abspath(bitstream)
    print(f"Running Vulkan decoder on {bitstream} ({max_frames} frames)...")
    result = subprocess.run(
        [str(EXAMPLE_BIN), abs_bitstream, str(max_frames)],
        cwd=str(TMP_DIR),
        capture_output=True,
        text=True,
        env=os.environ,
    )
    if result.returncode != 0:
        print("Vulkan decode failed!")
        print(result.stderr)
        sys.exit(1)
    print(result.stdout)

    # Verify output files exist (sort numerically by frame index)
    vulkan_files = sorted(glob.glob(str(TMP_DIR / f"{stem}_frame_*.yuv")), key=numeric_sort_key)
    if not vulkan_files:
        print("No YUV files generated by Vulkan decoder!")
        sys.exit(1)
    print(f"Vulkan decoder generated {len(vulkan_files)} YUV files.")
    return vulkan_files


def run_ffmpeg_decode(bitstream: str, max_frames: int):
    """Run ffmpeg to decode the same frames for reference."""
    stem = Path(bitstream).stem
    abs_bitstream = os.path.abspath(bitstream)
    out_pattern = f"{stem}_ffmpeg_frame_%d.yuv"

    print(f"Running ffmpeg decoder on {bitstream} ({max_frames} frames)...")
    cmd = [
        "ffmpeg", "-y", "-i", abs_bitstream,
        "-frames:v", str(max_frames),
        "-c:v", "rawvideo",
        "-pix_fmt", "yuv420p",
        "-f", "image2",
        out_pattern,
    ]
    result = subprocess.run(
        cmd,
        cwd=str(TMP_DIR),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("FFmpeg decode failed!")
        print(result.stderr)
        sys.exit(1)

    ffmpeg_files = sorted(glob.glob(str(TMP_DIR / out_pattern.replace("%d", "*"))), key=numeric_sort_key)
    if not ffmpeg_files:
        print("No YUV files generated by ffmpeg!")
        sys.exit(1)
    print(f"FFmpeg generated {len(ffmpeg_files)} YUV files.")
    return ffmpeg_files


def get_frame_size(filepath: str) -> tuple:
    """Detect frame width, height from YUV filename metadata or file size."""
    # We'll use ffmpeg to probe the source to get dimensions
    return None, None


def probe_dimensions(bitstream: str) -> tuple:
    """Get video dimensions using ffprobe."""
    cmd = [
        "ffprobe", "-v", "error",
        "-select_streams", "v:0",
        "-show_entries", "stream=width,height",
        "-of", "csv=p=0",
        bitstream,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ffprobe failed: {result.stderr}")
        sys.exit(1)
    lines = result.stdout.strip().split("\n")
    if len(lines) >= 1 and lines[0]:
        parts = lines[0].split(",")
        if len(parts) >= 2:
            return int(parts[0]), int(parts[1])
    print("Could not determine dimensions from ffprobe.")
    sys.exit(1)


def read_yuv(filepath: str, width: int, height: int) -> list:
    """Read YUV420P file into flat list of pixel values."""
    with open(filepath, "rb") as f:
        data = bytearray(f.read())
    return list(data)


def compute_psnr(yuv1: list, yuv2: list, width: int, height: int) -> float:
    """Compute PSNR between two YUV420P frames."""
    if len(yuv1) != len(yuv2):
        return float("nan")

    # Only use Y plane for PSNR (luma is perceptually dominant)
    y_size = width * height
    mse = 0.0
    for i in range(y_size):
        diff = yuv1[i] - yuv2[i]
        mse += diff * diff
    mse /= y_size

    if mse == 0:
        return float("inf")

    psnr = 10.0 * math.log10((255.0 ** 2) / mse)
    return psnr


def find_step(value: float) -> str:
    """Find which step bucket a PSNR value falls into."""
    for i in range(len(YUV_STEPS) - 1):
        if YUV_STEPS[i] <= value < YUV_STEPS[i + 1]:
            return f"[{YUV_STEPS[i]:g}..{YUV_STEPS[i+1]:g})"
    if value >= YUV_STEPS[-1]:
        return f"[{YUV_STEPS[-1]:g}..inf)"
    return f"[0..{YUV_STEPS[0]:g})"


def compare_frames(vulkan_files: list, ffmpeg_files: list, width: int, height: int) -> list:
    """Compare each pair of frames and compute PSNR."""
    results = []
    count = min(len(vulkan_files), len(ffmpeg_files))

    for i in range(count):
        vulkan_path = vulkan_files[i]
        ffmpeg_path = ffmpeg_files[i]

        v_data = read_yuv(vulkan_path, width, height)
        f_data = read_yuv(ffmpeg_path, width, height)
        psnr = compute_psnr(v_data, f_data, width, height)
        results.append({
            "frame": i,
            "vulkan": vulkan_path,
            "ffmpeg": ffmpeg_path,
            "psnr": psnr,
        })

    return results


def generate_report(results: list, bitstream: str, width: int, height: int):
    """Print a formatted comparison report."""
    print("\n" + "=" * 72)
    print("PIXEL VERIFICATION REPORT")
    print("=" * 72)
    print(f"Bitstream: {bitstream}")
    print(f"Resolution: {width}x{height}")
    print(f"Frames compared: {len(results)}")
    print("=" * 72)

    # Per-frame table
    print(f"\n{'Frame':>6}  {'PSNR (dB)':>12}  {'Step':>14}  {'Status':>10}")
    print("-" * 50)

    psnr_values = []
    for r in results:
        psnr = r["psnr"]
        psnr_values.append(psnr)

        if math.isinf(psnr):
            psnr_str = "inf"
            step_str = "perfect"
            status = "MATCH"
        elif math.isnan(psnr):
            psnr_str = "nan"
            step_str = "-"
            status = "ERROR"
        else:
            psnr_str = f"{psnr:.2f}"
            step_str = find_step(psnr)
            if psnr >= 45:
                status = "MATCH"
            elif psnr >= 35:
                status = "OK"
            elif psnr >= 25:
                status = "WARN"
            else:
                status = "FAIL"

        print(f"{r['frame']:>6}  {psnr_str:>12}  {step_str:>14}  {status:>10}")

    # Summary statistics
    finite_psnrs = [p for p in psnr_values if not math.isinf(p) and not math.isnan(p)]
    perfect_count = sum(1 for p in psnr_values if math.isinf(p))

    print("\n" + "-" * 50)
    print("SUMMARY")
    print("-" * 50)
    print(f"  Total frames:       {len(results)}")
    print(f"  Perfect match:      {perfect_count}")

    if finite_psnrs:
        avg = sum(finite_psnrs) / len(finite_psnrs)
        mn = min(finite_psnrs)
        mx = max(finite_psnrs)
        print(f"  Avg PSNR:           {avg:.2f} dB")
        print(f"  Min PSNR:           {mn:.2f} dB")
        print(f"  Max PSNR:           {mx:.2f} dB")

    # Step distribution
    step_counts = {}
    for p in psnr_values:
        if math.isinf(p):
            key = "perfect"
        else:
            key = find_step(p)
        step_counts[key] = step_counts.get(key, 0) + 1

    print("\n  Step distribution:")
    for step in YUV_STEPS:
        key = find_step(step)
        if key in step_counts:
            print(f"    {key:>16}: {step_counts[key]}")
    if "perfect" in step_counts:
        print(f"    {'perfect':>16}: {step_counts['perfect']}")

    # Overall verdict
    fail_count = sum(1 for r in results if not math.isinf(r["psnr"]) and r["psnr"] < 25)
    if fail_count > 0:
        print(f"\n  VERDICT: FAIL ({fail_count} frames below 25 dB)")
    elif perfect_count == len(results):
        print(f"\n  VERDICT: PASS (all frames perfect match)")
    else:
        print(f"\n  VERDICT: PASS")

    print("=" * 72)


def main():
    parser = argparse.ArgumentParser(
        description="Pixel-verify Vulkan decoder output against ffmpeg reference."
    )
    parser.add_argument("bitstream", help="Input bitstream file (.h264, .h265, .ivf)")
    parser.add_argument(
        "max_frames", nargs="?", type=int, default=20,
        help="Number of frames to decode (default: 20)",
    )
    parser.add_argument(
        "--keep-yuv", action="store_true",
        help="Keep generated YUV files after comparison",
    )
    args = parser.parse_args()

    bitstream = args.bitstream
    max_frames = args.max_frames

    if not os.path.exists(bitstream):
        print(f"Error: {bitstream} not found")
        sys.exit(1)

    stem = Path(bitstream).stem

    ensure_tmp_dir()

    # Step 1: Clean previous YUV files
    clean_yuv_files(stem)

    # Step 2: Build example
    build_example()

    # Step 3: Run Vulkan decoder
    vulkan_files = run_vulkan_decode(bitstream, max_frames)

    # Step 4: Run ffmpeg decoder
    ffmpeg_files = run_ffmpeg_decode(bitstream, max_frames)

    # Probe dimensions
    width, height = probe_dimensions(bitstream)
    print(f"Video dimensions: {width}x{height}")

    # Step 5: Compare frames
    results = compare_frames(vulkan_files, ffmpeg_files, width, height)

    # Step 6: Generate report
    generate_report(results, bitstream, width, height)

    # Cleanup
    if not args.keep_yuv:
        clean_yuv_files(stem)
    else:
        print(f"\nYUV files kept in {TMP_DIR}")


if __name__ == "__main__":
    main()
