#!/usr/bin/env python3
"""
Pixel-verification script for NVDEC (cuvid) decoder examples.

Runs the nvdec example (default: decode_nvdec_av1) to generate YUV frames in
/tmp/pixel_verify, decodes the same input with ffmpeg (software reference),
and compares frame-by-frame over the FULL YUV420P frame (all planes).

Usage:
    python3 pixel-verify-nvdec.py <bitstream> [max_frames] [example_name]
    python3 pixel-verify-nvdec.py assets/samples/av1_main.ivf 20 decode_nvdec_av1
"""

import argparse
import glob
import math
import os
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
TMP_DIR = Path("/tmp/pixel_verify")


def numeric_sort_key(path):
    stem = Path(path).stem
    parts = stem.rsplit("_", 1)
    if len(parts) == 2:
        try:
            return int(parts[1])
        except ValueError:
            pass
    return 0


def build_example(example_name: str):
    print(f"Building example {example_name} (--release)...")
    result = subprocess.run(
        ["cargo", "build", "--release", "--example", example_name],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("Build failed!")
        print(result.stderr)
        sys.exit(1)
    print("Build succeeded.")


def run_nvdec(example_name: str, bitstream: str, max_frames: int, stem: str):
    exe = PROJECT_ROOT / "target/release/examples" / example_name
    print(f"Running {example_name} on {bitstream} ({max_frames} frames)...")
    result = subprocess.run(
        [str(exe), os.path.abspath(bitstream), str(max_frames), stem],
        cwd=str(TMP_DIR),
        capture_output=True,
        text=True,
        env=os.environ,
    )
    if result.returncode != 0:
        print("NVDEC decode failed!")
        print(result.stdout[-4000:] if result.stdout else "")
        print(result.stderr[-4000:] if result.stderr else "")
        sys.exit(1)
    print(result.stdout[-3000:] if result.stdout else "")

    files = sorted(glob.glob(str(TMP_DIR / f"{stem}_frame_*.yuv")), key=numeric_sort_key)
    if not files:
        print("No YUV files generated by the NVDEC example!")
        sys.exit(1)
    print(f"NVDEC generated {len(files)} YUV files.")
    return files


def run_ffmpeg_decode(bitstream: str, max_frames: int, stem: str):
    out_pattern = f"{stem}_ffmpeg_frame_%d.yuv"
    print(f"Running ffmpeg decoder on {bitstream} ({max_frames} frames)...")
    cmd = [
        "ffmpeg", "-y", "-i", os.path.abspath(bitstream),
        "-frames:v", str(max_frames),
        "-c:v", "rawvideo",
        "-pix_fmt", "yuv420p",
        "-f", "image2",
        out_pattern,
    ]
    result = subprocess.run(cmd, cwd=str(TMP_DIR), capture_output=True, text=True)
    if result.returncode != 0:
        print("FFmpeg decode failed!")
        print(result.stderr)
        sys.exit(1)
    files = sorted(glob.glob(str(TMP_DIR / out_pattern.replace("%d", "*"))), key=numeric_sort_key)
    if not files:
        print("No YUV files generated by ffmpeg!")
        sys.exit(1)
    print(f"FFmpeg generated {len(files)} YUV files.")
    return files


def probe_dimensions(bitstream: str):
    cmd = [
        "ffprobe", "-v", "error",
        "-select_streams", "v:0",
        "-show_entries", "stream=width,height",
        "-of", "csv=p=0",
        bitstream,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ffprobe failed: {result.stderr}")
        sys.exit(1)
    parts = result.stdout.strip().split("\n")[0].split(",")
    return int(parts[0]), int(parts[1])


def compare_frames(nvdec_files, ffmpeg_files, width, height):
    results = []
    count = min(len(nvdec_files), len(ffmpeg_files))
    y_size = width * height
    frame_size = y_size * 3 // 2
    for i in range(count):
        with open(nvdec_files[i], "rb") as f:
            a = f.read()
        with open(ffmpeg_files[i], "rb") as f:
            b = f.read()
        if len(a) != len(b):
            results.append({"frame": i, "psnr": float("nan"), "maxdiff": -1,
                            "ndiff": -1, "size": (len(a), len(b))})
            continue
        n = min(len(a), frame_size)
        maxdiff = 0
        ndiff = 0
        mse_y = 0.0
        mse_u = 0.0
        mse_v = 0.0
        # Y plane
        for i2 in range(y_size):
            d = a[i2] - b[i2]
            if d:
                ndiff += 1
                ad = -d if d < 0 else d
                if ad > maxdiff:
                    maxdiff = ad
                mse_y += d * d
        # U plane
        for i2 in range(y_size, y_size + y_size // 4):
            d = a[i2] - b[i2]
            if d:
                ndiff += 1
                ad = -d if d < 0 else d
                if ad > maxdiff:
                    maxdiff = ad
                mse_u += d * d
        # V plane
        for i2 in range(y_size + y_size // 4, y_size + y_size // 2):
            d = a[i2] - b[i2]
            if d:
                ndiff += 1
                ad = -d if d < 0 else d
                if ad > maxdiff:
                    maxdiff = ad
                mse_v += d * d
        mse = (mse_y + mse_u + mse_v) / (y_size * 1.5)
        psnr = float("inf") if mse == 0 else 10.0 * math.log10((255.0 ** 2) / mse)
        results.append({"frame": i, "psnr": psnr, "maxdiff": maxdiff,
                        "ndiff": ndiff, "size": (len(a), len(b))})
    return results


def generate_report(results, bitstream, width, height):
    print("\n" + "=" * 72)
    print("NVDEC PIXEL VERIFICATION REPORT (full YUV420P comparison)")
    print("=" * 72)
    print(f"Bitstream: {bitstream}")
    print(f"Resolution: {width}x{height}")
    print(f"Frames compared: {len(results)}")
    print("=" * 72)
    print(f"\n{'Frame':>6}  {'PSNR (dB)':>12}  {'MaxDiff':>8}  {'DiffPix':>10}  {'Status':>10}")
    print("-" * 60)
    perfect = 0
    for r in results:
        if r["psnr"] == float("inf"):
            psnr_str, status = "inf", "PERFECT"
            perfect += 1
        elif math.isnan(r["psnr"]):
            psnr_str, status = "nan", "ERROR"
        else:
            psnr_str = f"{r['psnr']:.2f}"
            status = "PERFECT" if r["maxdiff"] == 0 else ("WARN" if r["psnr"] >= 35 else "FAIL")
        print(f"{r['frame']:>6}  {psnr_str:>12}  {r['maxdiff']:>8}  {r['ndiff']:>10}  {status:>10}")
    print("-" * 60)
    if perfect == len(results) and len(results) > 0:
        print(f"VERDICT: PASS ({perfect}/{len(results)} pixel-perfect)")
    else:
        print(f"VERDICT: FAIL ({perfect}/{len(results)} pixel-perfect)")
    print("=" * 72)
    return perfect == len(results) and len(results) > 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("bitstream")
    ap.add_argument("max_frames", nargs="?", type=int, default=20)
    ap.add_argument("example", nargs="?", default="decode_nvdec_av1")
    args = ap.parse_args()

    if not os.path.exists(args.bitstream):
        print(f"Error: {args.bitstream} not found")
        sys.exit(1)
    stem = Path(args.bitstream).stem
    TMP_DIR.mkdir(parents=True, exist_ok=True)

    # Clean previous outputs for this stem
    for pattern in (f"{stem}_frame_*.yuv", f"{stem}_ffmpeg_frame_*.yuv"):
        for p in glob.glob(str(TMP_DIR / pattern)):
            os.remove(p)

    build_example(args.example)
    nvdec_files = run_nvdec(args.example, args.bitstream, args.max_frames, stem)
    ffmpeg_files = run_ffmpeg_decode(args.bitstream, args.max_frames, stem)
    width, height = probe_dimensions(args.bitstream)
    print(f"Video dimensions: {width}x{height}")
    results = compare_frames(nvdec_files, ffmpeg_files, width, height)
    ok = generate_report(results, args.bitstream, width, height)
    sys.exit(0 if ok else 2)


if __name__ == "__main__":
    main()
