[package]
name = "vulkan-common"
description = "Common Vulkan device initialization and management"
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
vk-video-core = { workspace = true }
ash = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
