//! Test-only FFI bindings to the C++ differential-testing oracles
//! (`hevc/hevc_test_api.h`). Only used from unit tests.

#[allow(non_snake_case)]
unsafe extern "C" {
    pub fn hevcdec_test_transform_inverse(
        log2TrafoSize: i32,
        cIdx: i32,
        is_intra: i32,
        transform_skip: i32,
        bit_depth: i32,
        scaled: *const i16,
        residual: *mut i16,
    ) -> i32;

    pub fn hevcdec_test_dequant(
        bit_depth_luma: i32,
        bit_depth_chroma: i32,
        cIdx: i32,
        log2TrafoSize: i32,
        qp: i32,
        cu_is_intra: i32,
        use_scaling_list: i32,
        pps_scaling_list_present: i32,
        sl_data: *const u8,
        sl_dc: *const u8,
        pps_sl_data: *const u8,
        pps_sl_dc: *const u8,
        coefficients: *const i16,
        scaled: *mut i16,
    ) -> i32;

    pub fn hevcdec_test_interpolate_luma(
        plane: *const u16,
        picW: i32,
        picH: i32,
        stride: i32,
        xInt: i32,
        yInt: i32,
        xFrac: i32,
        yFrac: i32,
        nPbW: i32,
        nPbH: i32,
        bitDepth: i32,
        pred: *mut i16,
    ) -> i32;

    pub fn hevcdec_test_interpolate_chroma(
        plane: *const u16,
        cIdx: i32,
        picW: i32,
        picH: i32,
        stride: i32,
        xInt: i32,
        yInt: i32,
        xFrac: i32,
        yFrac: i32,
        nPbWC: i32,
        nPbHC: i32,
        bitDepth: i32,
        pred: *mut i16,
    ) -> i32;

    pub fn hevcdec_test_weighted_pred_default(
        predL0: *const i16,
        predL1: *const i16,
        flagL0: i32,
        flagL1: i32,
        nSamples: i32,
        bitDepth: i32,
        output: *mut i16,
    ) -> i32;

    pub fn hevcdec_test_weighted_pred_explicit(
        predL0: *const i16,
        predL1: *const i16,
        flagL0: i32,
        flagL1: i32,
        refIdxL0: i32,
        refIdxL1: i32,
        cIdx: i32,
        nSamples: i32,
        bitDepth: i32,
        luma_log2_weight_denom: u32,
        delta_chroma_log2_weight_denom: i32,
        w_luma: *const i16,
        o_luma: *const i16,
        w_chroma: *const i16,
        o_chroma: *const i16,
        output: *mut i16,
    ) -> i32;

    pub fn hevcdec_test_intra_predict(
        picW: i32,
        picH: i32,
        ctbSizeY: i32,
        minTbSizeY: i32,
        bitDepth: i32,
        chromaArrayType: i32,
        subW: i32,
        subH: i32,
        intra_smoothing_disabled: i32,
        strong_smoothing_enabled: i32,
        plane: *const u16,
        stride: i32,
        x0: i32,
        y0: i32,
        log2PredSize: i32,
        cIdx: i32,
        intra_mode: i32,
        pred: *mut i16,
    ) -> i32;

    pub fn hevcdec_test_cabac_run(
        data: *const u8,
        len_bytes: i32,
        slice_type: i32,
        qp: i32,
        cabac_init_flag: i32,
        ops: *const u8,
        args: *const i32,
        n_ops: i32,
        out: *mut i32,
        max_out: i32,
        final_range: *mut u16,
        final_offset: *mut u16,
        final_ctx: *mut u8,
    ) -> i32;

    pub fn hevcdec_test_sao_run(
        picW: i32,
        picH: i32,
        ctbLog2SizeY: i32,
        subW: i32,
        subH: i32,
        chromaArrayType: i32,
        bitDepthY: i32,
        bitDepthC: i32,
        sao_enabled: i32,
        pcm_filter_disabled: i32,
        transquant_bypass_enabled: i32,
        loop_filter_across_tiles: i32,
        tile_id: *const u8,
        ctb_addr_rs_to_ts: *const i32,
        plane_y: *const u16,
        plane_cb: *const u16,
        plane_cr: *const u16,
        stride_y: i32,
        stride_cb: i32,
        stride_cr: i32,
        slice_idx: *const u8,
        num_slices: i32,
        slice_across_slices: *const u8,
        sao_params: *const i32,
        cu_pcm: *const u8,
        cu_bypass: *const u8,
        out_y: *mut u16,
        out_cb: *mut u16,
        out_cr: *mut u16,
    ) -> i32;

    pub fn hevcdec_test_deblock_run(
        picW: i32,
        picH: i32,
        ctbLog2SizeY: i32,
        subW: i32,
        subH: i32,
        chromaArrayType: i32,
        bitDepthY: i32,
        bitDepthC: i32,
        pcm_filter_disabled: i32,
        loop_filter_across_tiles: i32,
        tile_id: *const u8,
        ctb_addr_rs_to_ts: *const i32,
        pps_cb_qp_offset: i32,
        pps_cr_qp_offset: i32,
        plane_y: *const u16,
        plane_cb: *const u16,
        plane_cr: *const u16,
        stride_y: i32,
        stride_cb: i32,
        stride_cr: i32,
        slice_idx: *const u8,
        num_slices: i32,
        sh_params: *const i32,
        cu_fields: *const i32,
        motion: *const i32,
        cbf_luma: *const u8,
        log2_tu_size: *const u8,
        edge_v: *const u8,
        edge_h: *const u8,
        poc_l0: *const i32,
        n_ref_l0: i32,
        poc_l1: *const i32,
        n_ref_l1: i32,
        out_y: *mut u16,
        out_cb: *mut u16,
        out_cr: *mut u16,
    ) -> i32;
}
