[package]
name = "examples"
description = "Examples for vk-video library"
license.workspace = true
version.workspace = true
edition.workspace = true
publish = false

[[example]]
name = "vulkan_decode"
path = "src/vulkan_decode.rs"

[[example]]
name = "vulkan_decode_vp9"
path = "src/vulkan_decode_vp9.rs"

[dependencies]
vk-video-core = { workspace = true }
vk-video-parser = { workspace = true }
vk-video-vulkan = { workspace = true }
nvdec-decode = { workspace = true }
ash = { workspace = true }
[[example]]
name = "decode_nvdec"
path = "src/decode_nvdec.rs"

[[example]]
name = "test_nvdec_edge"
path = "src/test_nvdec_edge.rs"
