[package]
name = "examples"
description = "Examples for vacc library"
license.workspace = true
version.workspace = true
edition.workspace = true
publish = false

[[example]]
name = "decode"
path = "src/decode.rs"

[dependencies]
vacc-core = { workspace = true }
vacc-parser = { workspace = true }
vacc-vulkan = { workspace = true }
nvdec-decode = { workspace = true }
vaapi-decode = { workspace = true }
vulkan-decode = { workspace = true }
 ash = { workspace = true }
