[package]
name = "vacc-nvdec-decode"
description = "NVDEC (NVIDIA Video Decode) backend for vacc"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
vacc-core = { workspace = true }
vacc-parser = { workspace = true }
vacc-vulkan = { workspace = true }
libloading = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }

[dev-dependencies]
ash = { workspace = true }
