[package]
name = "vulkan-decode"
description = "Vulkan Video Decode implementation with Decoder trait"
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
vk-video-core = { workspace = true }
vk-video-vulkan = { workspace = true }
ash = { workspace = true }
thiserror = { workspace = true }
