[package]
name = "vulkan-decode"
description = "Vulkan Video Decode implementation with Decoder trait"
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
vacc-core = { workspace = true }
vacc-vulkan = { workspace = true }
ash = { workspace = true }
thiserror = { workspace = true }
